backend:
  name: git-gateway
  branch: main

media_folder: "richemonte/webseite/images"
public_folder: "/images"

collections:
  - name: "seiten"
    label: "Seiten Inhalte"
    files:
      - file: "richemonte/webseite/index.html"
        label: "Hauptseite"
        name: "hauptseite"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}